### ISSUE TITLE
DB setup not working as expected

### ISSUE THREAD

**Issue by mariomaz87** [CodeWithCJ/SparkyFitness#1]
Hi,
I'm testing your application, it seems very cool! I have a problem with the deployment, in the docker logs I get (I have redacted the sensible information):

```
🚀 Starting Supabase project setup...

📦 Pushing DB migrations...

failed to parse connection string: cannot parse `postgresql://postgres:xxxxxx@43432413@db.43141413.supabase.co:5432/postgres`: failed to parse as URL (parse "postgresql://postgres:431431": invalid port ":J431413" after host)

Try rerunning the command with --debug to troubleshoot the error.

❌ DB push failed. You may need to run migration repair manually.

⚙️ Deploying Edge Functions...

🚀 Deploying function: chat

WARNING: Docker is not running

Uploading asset (chat): supabase/functions/chat/index.ts

Deployed Functions on project kyymlodmhaswfjiefwct: chat

You can inspect your deployment in the Dashboard: https://supabase.com/dashboard/project/kyymlodmhaswfjiefwct/functions

✅ Supabase backend setup attempted.

🌐 Proceeding with frontend deployment...

Listing dist directory contents:

total 40

drwxr-xr-x    2 root     root          4096 Jun 27 00:27 assets

-rwxr-xr-x    1 root     root         16958 Jun 27 00:27 favicon.ico

drwxr-xr-x    2 root     root          4096 Jun 27 00:27 images

-rw-r--r--    1 root     root          1376 Jun 27 00:27 index.html

-rwxr-xr-x    1 root     root           160 Jun 27 00:27 robots.txt

drwxr-xr-x    2 root     root          4096 Jun 27 00:27 videos

Listing dist/assets directory contents:

total 1652

-rw-r--r--    1 root     root         72756 Jun 27 00:27 index-BqRdT8lF.css

-rw-r--r--    1 root     root       1615811 Jun 27 00:27 index-CwrTC-U1.js

Files found by find:

dist/assets/index-CwrTC-U1.js

dist/assets/index-CwrTC-U1.js

 INFO  Accepting connections at http://localhost:3000
```

Probably something is not right in the variables of my docker compose:

```
    environment:
      NODE_ENV: production
      VITE_SUPABASE_URL: "the URL I get as "Project URL - A RESTful endpoint for querying and managing your database."
      VITE_SUPABASE_ANON_KEY: "the anon Key"
      SUPABASE_PROJECT_REF: "the Project ID I get in General Settings and also found in the URL"
      VITE_SUPABASE_DB_PASSWORD: "the DB password"
      #Below variable is optional. needed only to enable ChatBOT
      SUPABASE_ACCESS_TOKEN: "the sbp token"
```

I can access the web interface but I get "Error Failed to udpate" as soon as I change something.

Thanks!
